# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['stupidisco.py'],
    pathex=[],
    binaries=[],
    datas=[('icon.png', '.')],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'PyQt6.QtDBus',
        'PyQt6.QtNetwork',
        'PyQt6.QtPdf',
        'PyQt6.QtSvg',
        'PyQt6.QtOpenGL',
        'PyQt6.QtQml',
        'PyQt6.QtQuick',
        'PyQt6.QtTest',
        'PyQt6.QtMultimedia',
        'PyQt6.QtWebEngine',
        'PyQt6.QtWebEngineCore',
        'PyQt6.QtWebEngineWidgets',
        'PyQt6.QtDesigner',
        'PyQt6.QtHelp',
        'PyQt6.QtBluetooth',
        'PyQt6.QtNfc',
        'PyQt6.QtPositioning',
        'PyQt6.QtSensors',
        'PyQt6.QtSerialPort',
        'PyQt6.QtSql',
        'PyQt6.QtXml',
        'PyQt6.Qt3D',
        'pytest',
        'setuptools',
        'pkg_resources',
        'pygments',
        'unittest',
        'tkinter',
    ],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='stupidisco',
    debug=False,
    bootloader_ignore_signals=False,
    strip=True,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['icon.icns'],
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=True,
    upx=True,
    upx_exclude=[],
    name='stupidisco',
)
app = BUNDLE(
    coll,
    name='stupidisco.app',
    icon='icon.icns',
    bundle_identifier='io.celox.stupidisco',
    version='0.0.9',
    info_plist={
        'NSMicrophoneUsageDescription': 'stupidisco benötigt Mikrofonzugriff für die Live-Transkription von Interview-Fragen.',
        'NSHighResolutionCapable': True,
        'CFBundleShortVersionString': '0.0.9',
    },
)
